import{CANVAS_H,CANVAS_W,WORLD_MIN_X,WORLD_MAX_X,WORLD_MIN_Y,WORLD_MAX_Y,PAL,BUILDING_W,BUILDING_H,BUILDING_HP,BUILDING_SCORE,BUILDING_COLORS}from'./constants.js';
import{Renderer}from'./renderer.js';
import{drawRoad,drawGround,drawBuilding,drawHuman,drawBall,drawFlipper,drawParticle}from'./entities.js';
const canvas=document.getElementById('gameCanvas'),wrap=document.getElementById('wrap'),scoreEl=document.getElementById('score-display'),targetEl=document.getElementById('target-display'),destroyEl=document.getElementById('destroy-display'),fuelFill=document.getElementById('life-fill'),title=document.getElementById('title'),result=document.getElementById('result');
function scale(){wrap.style.transform=`scale(${Math.min(innerWidth/CANVAS_W,innerHeight/CANVAS_H)})`}addEventListener('resize',scale);scale();
let renderer;try{renderer=new Renderer(canvas)}catch(e){result.textContent='WEBGL2 REQUIRED';result.classList.add('show');throw e}
const buf=renderer.buf,MAXB=32,MAXH=96,MAXP=512;
const bt=new Int8Array(MAXB),btar=new Int8Array(MAXB),ba=new Int8Array(MAXB),bhp=new Int8Array(MAXB),bx=new Float32Array(MAXB),by=new Float32Array(MAXB),bf=new Float32Array(MAXB);let bc=0;
const ha=new Int8Array(MAXH),hx=new Float32Array(MAXH),hy=new Float32Array(MAXH),hvx=new Float32Array(MAXH),hvy=new Float32Array(MAXH);let hc=0;
const pl=new Float32Array(MAXP),px=new Float32Array(MAXP),py=new Float32Array(MAXP),pvx=new Float32Array(MAXP),pvy=new Float32Array(MAXP),pr=new Float32Array(MAXP),pg=new Float32Array(MAXP),pb=new Float32Array(MAXP);
let ballX=0,ballY=-210,ballVx=0,ballVy=8,pressed=false,started=false,cleared=false,gameOver=false,fuel=100,score=0,last=0;
function addB(t,x,y,target){const i=bc++;bt[i]=t;bx[i]=x;by[i]=y;btar[i]=target;ba[i]=1;bhp[i]=BUILDING_HP[t];bf[i]=0}
function reset(){bc=0;addB(0,-142,-220,0);addB(1,-104,-216,0);addB(2,-66,-224,0);addB(5,-12,-218,1);addB(0,48,-220,0);addB(0,104,-218,0);addB(4,-132,-118,0);addB(3,-92,-114,0);addB(3,-50,-114,0);addB(6,12,-128,1);addB(1,82,-116,0);addB(2,132,-124,0);addB(0,-142,-22,0);addB(0,-100,-20,0);addB(4,-52,-24,0);addB(7,26,-34,1);addB(3,106,-22,0);addB(0,150,-20,0);addB(8,-104,88,1);addB(9,-12,82,1);addB(6,82,92,0);addB(5,144,100,0);hc=60;for(let i=0;i<hc;i++){ha[i]=1;hx[i]=-160+Math.random()*320;hy[i]=-175+Math.random()*310;hvx[i]=(Math.random()*2-1)*18;hvy[i]=(Math.random()*2-1)*18}for(let i=0;i<MAXP;i++)pl[i]=0;ballX=0;ballY=-210;ballVx=0;ballVy=8;fuel=100;score=0;started=false;cleared=false;gameOver=false;title.classList.add('show');result.classList.remove('show');hud()}
function targetDone(){let n=0;for(let i=0;i<bc;i++)if(btar[i]&&!ba[i])n++;return n}
function destroyRatio(){let live=0;for(let i=0;i<bc;i++)if(ba[i])live++;return(bc-live)/bc}
function hud(){scoreEl.textContent=`SCORE ${score.toLocaleString()}`;targetEl.textContent=`TARGET ${targetDone()}/3`;destroyEl.textContent=`DEST ${Math.floor(destroyRatio()*100)}%`;fuelFill.style.width=`${Math.max(0,Math.min(100,fuel))}%`}
function spawn(x,y,c){for(let i=0;i<MAXP;i++){if(pl[i]<=0){pl[i]=.45+Math.random()*.25;px[i]=x;py[i]=y;pvx[i]=(Math.random()*2-1)*100;pvy[i]=(Math.random()*2-1)*100;pr[i]=c[0];pg[i]=c[1];pb[i]=c[2];return}}}
function hitB(i){const t=bt[i],w=BUILDING_W[t],h=BUILDING_H[t],nx=Math.max(bx[i]-w/2,Math.min(ballX,bx[i]+w/2)),ny=Math.max(by[i],Math.min(ballY,by[i]+h)),dx=ballX-nx,dy=ballY-ny;return dx*dx+dy*dy<=256}
function damage(i){const t=bt[i];bhp[i]--;bf[i]=.08;ballVx+=(ballX-bx[i])*.035;ballVy*=-.72;if(bhp[i]<=0&&ba[i]){ba[i]=0;score+=BUILDING_SCORE[t]*(btar[i]?3:1);fuel=Math.min(100,fuel+(btar[i]?18:6));for(let k=0;k<24;k++)spawn(bx[i],by[i]+BUILDING_H[t]/2,BUILDING_COLORS[t])}}
function flp(left){const x=left?-86:86,y=-230,base=left?-.46:Math.PI+.46,a=base+(pressed?(left?.9:-.9):0);return{x1:x,y1:y,x2:x+Math.cos(a)*68,y2:y+Math.sin(a)*68,left}}
function resF(left){const f=flp(left),dx=f.x2-f.x1,dy=f.y2-f.y1,t=Math.max(0,Math.min(1,((ballX-f.x1)*dx+(ballY-f.y1)*dy)/(dx*dx+dy*dy))),x=f.x1+dx*t,y=f.y1+dy*t,ox=ballX-x,oy=ballY-y,d=Math.hypot(ox,oy);if(d<20){const nx=ox/(d||1),ny=oy/(d||1),p=pressed?11:4;ballX=x+nx*20;ballY=y+ny*20;ballVx+=nx*p+(left?3:-3);ballVy+=ny*p+(pressed?12:3)}}
function update(dt){if(!started||cleared||gameOver)return;fuel-=dt*3.2;if(fuel<=0){fuel=0;gameOver=true;result.textContent='GAME OVER\nTAP / CLICK TO RETRY';result.classList.add('show');hud();return}ballVy-=.22*55*dt;ballX+=ballVx*60*dt;ballY+=ballVy*60*dt;ballVx*=.994;ballVy*=.994;if(ballX<WORLD_MIN_X+16){ballX=WORLD_MIN_X+16;ballVx=Math.abs(ballVx)*.72}if(ballX>WORLD_MAX_X-16){ballX=WORLD_MAX_X-16;ballVx=-Math.abs(ballVx)*.72}if(ballY>WORLD_MAX_Y-16){ballY=WORLD_MAX_Y-16;ballVy=-Math.abs(ballVy)*.72}if(ballY<WORLD_MIN_Y-34){ballX=0;ballY=-210;ballVx=0;ballVy=8;fuel=Math.max(0,fuel-12)}resF(true);resF(false);for(let i=0;i<bc;i++){if(bf[i]>0)bf[i]=Math.max(0,bf[i]-dt);if(ba[i]&&hitB(i))damage(i)}for(let i=0;i<hc;i++){if(!ha[i])continue;hx[i]+=hvx[i]*dt;hy[i]+=hvy[i]*dt;if(hx[i]<-165||hx[i]>165)hvx[i]*=-1;if(hy[i]<-185||hy[i]>145)hvy[i]*=-1;const dx=hx[i]-ballX,dy=hy[i]-ballY;if(dx*dx+dy*dy<400){ha[i]=0;score+=10;fuel=Math.min(100,fuel+2);spawn(hx[i],hy[i],PAL.blood)}}for(let i=0;i<MAXP;i++)if(pl[i]>0){px[i]+=pvx[i]*dt;py[i]+=pvy[i]*dt;pl[i]-=dt;pvy[i]-=110*dt}if(targetDone()>=3&&destroyRatio()>=.8){cleared=true;score+=5000;result.textContent='STAGE CLEAR!\nTAP / CLICK TO RETRY';result.classList.add('show')}hud()}
function render(){const gl=renderer.gl;gl.clearColor(.04,.035,.05,1);gl.clear(gl.COLOR_BUFFER_BIT);renderer.drawBackground(PAL.skyTop,PAL.skyBot);let idx=0;idx=drawRoad(buf,idx,-170);idx=drawRoad(buf,idx,-70);idx=drawRoad(buf,idx,30);idx=drawRoad(buf,idx,140);idx=drawGround(buf,idx);for(let i=0;i<bc;i++)idx=drawBuilding(buf,idx,bt[i],bx[i],by[i],bhp[i],ba[i],btar[i],bf[i],BUILDING_W[bt[i]],BUILDING_H[bt[i]]);for(let i=0;i<hc;i++)if(ha[i])idx=drawHuman(buf,idx,hx[i],hy[i]);for(let i=0;i<MAXP;i++)if(pl[i]>0)idx=drawParticle(buf,idx,px[i],py[i],pr[i],pg[i],pb[i],Math.max(0,pl[i]*2));const lf=flp(true),rf=flp(false);idx=drawFlipper(buf,idx,lf.x1,lf.y1,lf.x2,lf.y2);idx=drawFlipper(buf,idx,rf.x1,rf.y1,rf.x2,rf.y2);idx=drawBall(buf,idx,ballX,ballY);renderer.draw(idx)}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);render();requestAnimationFrame(loop)}
function start(){if(!started||cleared||gameOver){reset();started=true;title.classList.remove('show');result.classList.remove('show')}pressed=true}
addEventListener('mousedown',start);addEventListener('mouseup',()=>pressed=false);addEventListener('touchstart',e=>{e.preventDefault();start()},{passive:false});addEventListener('touchend',e=>{e.preventDefault();pressed=false},{passive:false});addEventListener('keydown',e=>{if(!e.repeat)start()});addEventListener('keyup',()=>pressed=false);reset();requestAnimationFrame(t=>{last=t;requestAnimationFrame(loop)});
