import{CANVAS_H,CANVAS_W,INST_FLOATS,MAX_INSTANCES,WORLD_MAX_X,WORLD_MAX_Y,WORLD_MIN_X,WORLD_MIN_Y}from'./constants.js';
const VS=`#version 300 es
precision highp float;in vec2 a_vert;in vec2 i_pos;in vec2 i_size;in vec4 i_color;in float i_rot;in float i_shape;in vec4 i_params;in float i_glow;in float i_soft;uniform mat4 u_proj;out vec2 v_uv;out vec4 v_color;out float v_shape;out vec4 v_params;out float v_glow;out float v_soft;void main(){float c=cos(i_rot),s=sin(i_rot);vec2 q=a_vert*i_size;vec2 r=vec2(c*q.x-s*q.y,s*q.x+c*q.y);gl_Position=u_proj*vec4(r+i_pos,0.0,1.0);v_uv=a_vert;v_color=i_color;v_shape=i_shape;v_params=i_params;v_glow=i_glow;v_soft=i_soft;}`;
const FS=`#version 300 es
precision highp float;in vec2 v_uv;in vec4 v_color;in float v_shape;in vec4 v_params;in float v_glow;in float v_soft;out vec4 outColor;float bx(vec2 p,vec2 b){vec2 q=abs(p)-b;return length(max(q,0.0))+min(max(q.x,q.y),0.0);}float rb(vec2 p,vec2 b,float r){vec2 q=abs(p)-b+r;return length(max(q,0.0))+min(max(q.x,q.y),0.0)-r;}float cc(vec2 p,float r){return length(p)-r;}float capx(vec2 p,float h,float r){p.x-=clamp(p.x,-h,h);return length(p)-r;}float capy(vec2 p,float h,float r){p.y-=clamp(p.y,-h,h);return length(p)-r;}float tri(vec2 p){p.y+=.08;vec2 q=abs(p);return max(q.x*.866+p.y*.5,-p.y)-.36;}void main(){vec2 p=v_uv;float sh=floor(v_shape+.5);float d=0.;if(sh==0.)d=bx(p,vec2(.5));else if(sh==1.)d=rb(p,vec2(.5),v_params.x);else if(sh==2.)d=cc(p,.5);else if(sh==3.)d=v_params.x<.5?capx(p,.34,.16):capy(p,.34,.16);else if(sh==4.)d=v_params.x<.5?tri(p):tri(vec2(p.x,-p.y));else if(sh==5.)d=max(cc(p,.5),-cc(p,.5-max(.02,min(.45,v_params.x))));else d=cc(p,.5);float soft=max(.001,v_soft);float a=v_color.a*(1.-smoothstep(-soft,soft,d));vec3 rgb=v_color.rgb;if(v_glow>0.){float g=exp(-max(d,0.)*18.)*v_glow;rgb+=v_color.rgb*g;a=max(a,g*.55*v_color.a);}outColor=vec4(rgb,a);}`;
const BGV=`#version 300 es
in vec2 a_pos;out vec2 v_uv;void main(){gl_Position=vec4(a_pos,0.0,1.0);v_uv=a_pos*.5+.5;}`;
const BGF=`#version 300 es
precision mediump float;uniform vec4 u_top;uniform vec4 u_bot;in vec2 v_uv;out vec4 outColor;void main(){outColor=mix(u_bot,u_top,v_uv.y);}`;
function compile(gl,t,s){const sh=gl.createShader(t);gl.shaderSource(sh,s);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh)||'shader');return sh}
function link(gl,v,f){const p=gl.createProgram();gl.attachShader(p,compile(gl,gl.VERTEX_SHADER,v));gl.attachShader(p,compile(gl,gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'program');return p}
function ortho(l,r,b,t){return new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-1,0,-(r+l)/(r-l),-(t+b)/(t-b),0,1])}
export class Renderer{constructor(canvas){const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance'});if(!gl)throw new Error('WebGL2 required');this.gl=gl;this.buf=new Float32Array(MAX_INSTANCES*INST_FLOATS);this.proj=ortho(WORLD_MIN_X,WORLD_MAX_X,WORLD_MIN_Y,WORLD_MAX_Y);this.prog=link(gl,VS,FS);this.bgProg=link(gl,BGV,BGF);this.vao=gl.createVertexArray();gl.bindVertexArray(this.vao);const quad=new Float32Array([-.5,-.5,.5,-.5,-.5,.5,.5,.5]);const qbo=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,qbo);gl.bufferData(gl.ARRAY_BUFFER,quad,gl.STATIC_DRAW);let loc=gl.getAttribLocation(this.prog,'a_vert');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);this.instVbo=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.instVbo);gl.bufferData(gl.ARRAY_BUFFER,this.buf.byteLength,gl.DYNAMIC_DRAW);const stride=INST_FLOATS*4;const attr=(n,z,o)=>{const l=gl.getAttribLocation(this.prog,n);gl.enableVertexAttribArray(l);gl.vertexAttribPointer(l,z,gl.FLOAT,false,stride,o*4);gl.vertexAttribDivisor(l,1)};attr('i_pos',2,0);attr('i_size',2,2);attr('i_color',4,4);attr('i_rot',1,8);attr('i_shape',1,9);attr('i_params',4,10);attr('i_glow',1,14);attr('i_soft',1,15);gl.bindVertexArray(null);this.bgVao=gl.createVertexArray();gl.bindVertexArray(this.bgVao);const bgbo=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,bgbo);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW);loc=gl.getAttribLocation(this.bgProg,'a_pos');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);gl.bindVertexArray(null);this.uProj=gl.getUniformLocation(this.prog,'u_proj');this.uTop=gl.getUniformLocation(this.bgProg,'u_top');this.uBot=gl.getUniformLocation(this.bgProg,'u_bot');gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.viewport(0,0,CANVAS_W,CANVAS_H)}drawBackground(top,bot){const gl=this.gl;gl.useProgram(this.bgProg);gl.uniform4f(this.uTop,top[0],top[1],top[2],top[3]);gl.uniform4f(this.uBot,bot[0],bot[1],bot[2],bot[3]);gl.bindVertexArray(this.bgVao);gl.drawArrays(gl.TRIANGLE_STRIP,0,4)}draw(count){const gl=this.gl;gl.useProgram(this.prog);gl.uniformMatrix4fv(this.uProj,false,this.proj);gl.bindVertexArray(this.vao);gl.bindBuffer(gl.ARRAY_BUFFER,this.instVbo);gl.bufferSubData(gl.ARRAY_BUFFER,0,this.buf,0,count*INST_FLOATS);gl.drawArraysInstanced(gl.TRIANGLE_STRIP,0,4,count)}}
export function writeInst(buf,idx,x,y,w,h,c,rot,shape,p0=0,p1=0,p2=0,p3=0,glow=0,soft=.006){const o=idx*INST_FLOATS;buf[o]=x;buf[o+1]=y;buf[o+2]=w;buf[o+3]=h;buf[o+4]=c[0];buf[o+5]=c[1];buf[o+6]=c[2];buf[o+7]=c[3];buf[o+8]=rot;buf[o+9]=shape;buf[o+10]=p0;buf[o+11]=p1;buf[o+12]=p2;buf[o+13]=p3;buf[o+14]=glow;buf[o+15]=soft;return idx+1}
